server:
  tomcat.mbeanregistry.enabled: true
debug: false
management.endpoints.web.exposure.include: "prometheus"

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type.descriptor.sql.BasicBinder: trace
  org.springframework.web.servlet: info
  org.springframework.jdbc.core.JdbcTemplate: DEBUG
  org.springframework.jdbc.core.StatementCreatorUtils: TRACE

springdoc:
  show-actuator: true

spring:
  mvc:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET, POST, PUT, DELETE"
  application.name: orury-client
  datasource:
    read:
      jdbc-url: ENC(KkrDs/i2Asal3Qe2/GRo7vBh3Jdu3ozFVNy6sQzXYwKLScBRkm4jB4uWWCBF+rm/2t2XWE67sKRNXyL5fOChWLZ3hmp6KsMo4JSGjwXG8lzcStqVPMQ8jRq+cjaEALI4)
      username: ENC(VUKxrYEb2eEVncT0XD7eeg==)
      password: ENC(cGqwrzSfPJ96ZWhzjecvMoL80gulmH1r)
      driver-class-name: com.mysql.cj.jdbc.Driver
    write:
      jdbc-url: ENC(nYHDbyPX77wt52BMec5vJQLAWDcuiHS06QrV34A4AoEjrCnmNAmWNO/x0FUvNmvRhCPhaPkS1z9bhK7lyRVKocHukRjc5jwbf0XiceDDO2OtxDAfSPTvZg==)
      username: ENC(VUKxrYEb2eEVncT0XD7eeg==)
      password: ENC(cGqwrzSfPJ96ZWhzjecvMoL80gulmH1r)
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
    hibernate.ddl-auto: validate
    open-in-view: false

  sql.init.mode: always

  devtools:
    livereload:
      enabled: true
  servlet:
    multipart:
      maxFileSize: 5MB # 파일 하나의 최대 크기
      maxRequestSize: 25MB  # 한 번에 최대 업로드 가능 용량
  jwt:
    secret:
      ENC(s+e66U0YV1+iNWMLFl0LCHmARANd5yCv3k41u0iPDpCyfG7+PUgpsYNyUP7SFk/PUNPuK/wnNod399PK2kW+qllbWZzqNwp6msfDx1xP8DCiTHCZXE4rcNZDYji0bM9uzyxIDCGMyDE=)
  jackson:
    property-naming-strategy: SNAKE_CASE
cloud:
  aws:
    s3:
      bucket: ENC(DWaoEy70NtH+lhLIr08FR4qd/T11UK+X)
      default-image: default-user-profile
      url: https://s3.ap-northeast-2.amazonaws.com/
    credentials:
      accessKey: ENC(yfr+1GPLxMHuTbbID6K7Jbs0Dm9iuuK9yFjrOJv8jCU=)
      secretKey: ENC(nnQ4XTkipeaA+bE6zKD6kI04Axa+E2Qjmw081EgZHpPXhPEBV/dgwqf9YeN1a0vJebMq0yceQJQ=)
    region:
      static: ap-northeast-2
jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}

slack:
  token: ENC(7Pd4U/iPDtDF5quQM5TzMXF7jsfv+QQYCDdckH+/T8vbz/QOYTOKX6iAGdqM5gRVusZ84cC93RpQE8qK1kW4f6tdoIf5GDu2)
  channel: ENC(9i8/M3HKZDCGoJWCM1B1Lg6ECmK4eudW)

decorator:
  datasource:
    p6spy:
      enable-logging: true
---
spring:
  profiles:
    include: secret, dev
---
oauth-login:
  client:
    apple-auth:
      url: https://appleid.apple.com
    kakao-auth:
      url: https://kauth.kakao.com
    kakao-kapi:
      url: https://kapi.kakao.com
  provider:
    apple:
      grant-type: authorization_code
      client-id: ENC(IsmSK+WGaIMSbqooHIKuIf/+ohtA3cg+)
      key-id: ENC(brcOV0kbT6t3WxbIHtYm3koGXRqre5QP)
      team-id: ENC(Yj5y1FXFku6D8rUcrqyzykhtkE48AGM+)
      audience: https://appleid.apple.com
      private-key: ENC(B1eHssqHQ+ATb9OF6jB3jxREnGj6u5Mu2wsN2JwYMJRWhocKJ/YvhOutzZaSMgpMOAA0SJgPvi7FOJCQJ5NCOoA+tLvpy13zRRSZuVSyq/gQZXH0O9MwrXHoLp4shh+V6+Nuk0H1iJelSrW7b3H8cDqFYJ/fOXFap9nSfsKkuo4u+dkwPyh2XGmyTHbJUqOtUIj11c4NcJjpVGLJSrvV6NtSYWbhnSXZidqJQkVwFMQFXNsEIAU+R7iZxsQyJ3eR3XfLPqLs9GBA+kfObDrGqh//wpGBkYHV)
    kakao:
      grant-type: authorization_code
      client-id: ENC(pgz2ivbzAfICX0Nilz7oi7v6ymwehNeaXussHnvSA2HPT9hUt/UWJpZON6xxG0ia)
      redirect-uri: ENC(/eNjHHXCQ9OALM/3dDH3B15hSqiMzm/6ej3G44fPl8YDJSlajeVLnOzLqzVQv5gx)
      client-secret: ENC(5WX5kqJUy9bVfT4XdBxhLqtcJqEPdgMHGaJl79j1l96IWd5rwRBJ1UlsWzvyRuSJ)
      content-type: application/x-www-form-urlencoded;charset=utf-8